### ISSUE TITLE
Add implementation for helm test

### ISSUE THREAD

**Issue by chagantibhaskar** [Typositoire/concourse-helm3-resource#23]
I will be soon starting on implementing the helm test feature, which is right now "To be Implemented".
I am curious to know if you or anyone who have forked this repo are on the way to put in an implementation any time soon?

Do you have any ideas/directions around the implementation?

**Comment by Typositoire** [comment]
I don't know anyone that is working on that. Thanks for doing it!
As for implementation here's my take on it, but i'm open to anything. I guess if `test = true`, you would run helm test after the deployment has been done. And maybe a test_only flag to test deployments that are deployed, to have pipeline be able to test deployment regardless of if it was deployed by that pipeline?

**Comment by Typositoire** [comment]
@cqwense I had a vision xD What would you think if we added that to the check being disabled by default but we could make it so that the implicit get of a put could make the helm test?

```
put: my_release
get_params:
  test: true
```

**Comment by cqwense** [comment]
I can see what you're going for, and it should work.  before i force push updated my branch removing repos from check I had been trying to work on normalizing check for dynamic namespace/release.name combinations and realized i'd gone down the wrong track - I think fixing those issues will also apply here , because at the moment we'd need to pass both values dynamically to the get_params, and it would look like:

put: my_cluster
  release: 'example'
  namespace: 'namespace1'
get_params:
  release: 'example'
  namesapce: 'namespace1' 
  test: true

because none of the standard version output includes namespace, we can't really use the version hash passed to in by default ( yet ) 

i'm on vacation, but gimmie a few days i'll see what I come up with 👍

**Comment by cqwense** [comment]
It would also probably hard-require check_is_ready on the put, otherwise the put would return before the release is 100% deployed, which would invalidate any helm_test ran.

**Comment by Typositoire** [comment]
All good, take your time and enjoy you vacations :p Let's try to coordinate
on collaboration for this one. What timezone are you in?
