### ISSUE TITLE
Possible Bug: Setting `stable_repo` to false doesn't do anything?

### ISSUE THREAD

**Issue by Typositoire** [Typositoire/concourse-helm3-resource#48]
When setting `stable_repo` to false it still add the stable repo, could be caching issue or base image that adds it ?

**Comment by cqwense** [comment]
shall give this a better look soon(tm)

**Comment by cqwense** [comment]
at the moment you have to to 

`stable_repo: "false"` 
or
`stable_repo: 'false'

as opposed to 

`stable_repo: false` 

basically set it as a string false, vs the bool false - because if jq gets a bool false we set stable_repo to the string for helm.sh url

not 100% sure what to do about it atm.

https://github.com/Typositoire/concourse-helm3-resource/blob/master/assets/common.sh#L108

**Comment by Typositoire** [comment]
It's possible. We tested in quick in a failure scenario so it would have been us being derp xD I'll close it for now and assume we did it wrong. Thanks for looking at this!
